ckeditor/ckeditor5-heading

src/headings.js, tests/headings.js
=> Added view focusing after headings command is executed from dropdown.

src/headings.js
Part of https://github.com/ckeditor/ckeditor5-ui-default/issues/30.
=> Use DropdownModel#withText attribute in Headings feature

tests/manual/headings.js
Fixes: https://github.com/ckeditor/ckeditor5-typing/issues/17
Depends on: https://github.com/ckeditor/ckeditor5-typing/pull/24
=> Fixed tests after package merged.

src/headingsengine.js
Fixes: https://github.com/ckeditor/ckeditor5-engine/issues/467
Depends on: https://github.com/ckeditor/ckeditor5-engine/pull/524
=> Renamed converter builders to lowerCase.

src/headings.js, src/headingscommand.js, src/headingsengine.js, tests/headings.js, tests/headingscommand.js, tests/headingsengine.js
=> Changed paths and docs to use ckeditor5-core package

.jshintrc, tests/.jshintrc, tests/headings.js, tests/manual/headings.js
=> Turn JSHint browser setting to false.

tests/headingscommand.js
Fixes https://github.com/ckeditor/ckeditor5-engine/issues/306
Depends on: https://github.com/ckeditor/ckeditor5-engine/pull/554
=> Refactored model utils.

tests/manual/headings.html
=> Fixed path to ckeditor.css

src/headingscommand.js
Changes required by ckeditor5-engine/585.
=> Changed: parameters order in RenameDelta.

src/heading.js, src/headingcommand.js, tests/heading.js, tests/headingcommand.js
Fixes: #36.
Added batch option. Updated automated tests.
=> Updated _doExecute method to use options object

src/heading.js, tests/heading.js
Closes #41.
Requires https://github.com/ckeditor/ckeditor5-ui/pull/100.
=> t/41: Updated heading after the removal of Controller class.

src/heading.js, tests/heading.js
=> t/48: MVC refactoring followups.

src/heading.js, tests/heading.js
Feature: Marked active heading in the drop-down list. Closes #26.
---
* Requires https://github.com/ckeditor/ckeditor5-heading/pull/59.
* Requires https://github.com/ckeditor/ckeditor5-ui/pull/167.
* Requires https://github.com/ckeditor/ckeditor5-theme-lark/pull/81.
=> T/26: Marked active heading in the drop-down list

src/heading.js, tests/heading.js
Feature: Enabled the tooltip for the 'headings' component in editor.ui#componentFactory. Closes #55.
---
Requires https://github.com/ckeditor/ckeditor5-heading/pull/60.
=> t/55: Enabled the tooltip for the 'headings' component in editor.ui#componentFactory.

lang/contexts.json, src/heading.js, tests/heading.js
Fix: The default dropdown label should not equal 'Paragraph'. Closes #62.
=> t/62: The default dropdown label should not be 'Paragraph'. Closes #62.

lang/contexts.json, src/heading.js, tests/heading.js, theme/theme.scss
Fix: Changed default heading dropdown title to more meaningful. Closes #68.
=> Changed default heading dropdown title.

src/headingcommand.js, tests/heading.js, tests/headingcommand.js
Fix: Dropdown is inactive when none of the commands can be applied. Closes #66 .
---
Please close first:
#69 
https://github.com/ckeditor/ckeditor5-paragraph/pull/17
=> T/66 Dropdown should be not active and have default title on images

tests/integration.js
Internal: Aligned selection method names to the changes in the engine.
=> Align selection method names to the changes in the engine

tests/manual/heading.js
Tests: Minor adjustment in toolbar configuration (see ckeditor/ckeditor5#645).
---
* A piece of https://github.com/ckeditor/ckeditor5/issues/645.
=> t/ckeditor5/645: Minor adjustment in toolbar configuration

src/headingengine.js, tests/headingengine.js
Other: Aligning with new conversion helpers API.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
=>  Other: Aligning with new conversion helpers API

docs/_snippets/features/custom-heading-elements.js, docs/_snippets/features/custom-heading-levels.js, package.json
Docs: Upload images will work on all snippets. See ckeditor/ckeditor5#901.
=> Upload images will work on all snippets

src/headingcommand.js, tests/headingcommand.js
Other: Remove silent validation in commands.
---
* I've used the editor will fail approach as this happen.
=> Other: Remove silent validation in commands.

docs/_snippets/features/custom-heading-elements.js, docs/features/headings.md, tests/headingediting.js, tests/integration.js
Internal: Aligned to the changes in the engine. See ckeditor/ckeditor5#742.
Requires: https://github.com/ckeditor/ckeditor5-engine/pull/1389.
=> Aligned to the changes in engine

src/utils.js
Internal: Simplified obtaining the editor configuration (see ckeditor/ckeditor5-utils#257).
=> t/ckeditor-utils/257: Simplified obtaining the editor configuration

src/utils.js
Docs: Add missing docs entry for utils.
=> Docs: Add missing docs entry

docs/features/title.md, lang/contexts.json, src/title.js, tests/manual/title.html, tests/manual/title.js, tests/manual/title.md, tests/title.js
Internal: Introduce configuration option to overwrite title placeholder text. Closes https://github.com/ckeditor/ckeditor5/issues/2472.
=> Introduce configuration option to overwrite title placeholder text.
